SUMM_INPUT = 'Enter loan amount'
PERCENT_INPUT = 'Enter interest rate'
PERIOD_INPUT = 'Enter the loan term (in years)'
PAYMENT_PRINT = 'Payment'
TOTAL_LOAN_AMOUNT = 'The total loan amount will be'

REVENUE_INPUT = 'Enter your monthly revenue'
TYPE_COST_INPUT = 'Enter type cost or "done" to finish'
AMOUNT_INPUT = 'Enter amount for '
REVENUE_OUTPUT = 'Revenue'
TOTAL_COST = 'Total Cost'
PROFIT = 'Profit'
PROFITABILITY = 'Profitability'
WORD_BREAK = 'done'
BAD_PROFITABILITY = 'Close your busieness!'
GOOD_PROFITABILITY = 'We advise you to find a way to reduce costs or increase income.'
GREAT_PROFITABILITY = 'What kind of business, b####?'