SUMM_INPUT = 'Введите сумму кредита'
PERCENT_INPUT = 'Введите процентную ставку'
PERIOD_INPUT = 'Введите срок кредитования (в годах)'
PAYMENT_PRINT = 'Платёж'
TOTAL_LOAN_AMOUNT = 'Общая сумма кредита составит'

REVENUE_INPUT = 'Введите вашу месячную выручку'
TYPE_COST_INPUT = 'Введите тип затрат или "готово", чтобы закончить '
AMOUNT_INPUT = 'Введите величину затрат на '
REVENUE_OUTPUT = 'Выручка'
TOTAL_COST = 'Обшие затраты'
PROFIT = 'Прибыль'
PROFITABILITY = 'Рентабельность'
WORD_BREAK = 'готово'